image: Visual Studio 2019

services:
  - mssql2016

shallow_clone: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Debaser -c Release 
  - dotnet build Debaser.Tests -c Release 
